[project]
name = "aegis_core"
version = "0.1.0"
description = "A multi-framework blueprint for production-grade AI..."
authors = [
    { name = "Jules", email = "jules@example.com" }
]
requires-python = ">=3.11"

[project.dependencies]
# Core
pydantic = "~=2.7"
python-dotenv = "~=0.21"
fastapi = "~=0.111"
uvicorn = "~=0.29"
google-generativeai = "~=0.5"

# Framework 1 (LangGraph)
langchain = "~=0.1"
langgraph = "~=0.0.48"
langchain-google-genai = "~=1.0"

# Framework 2 (Genkit)
google-genkit = "~=0.2"

# Framework 3 (ADK)
google-cloud-adk = "~=0.2"
google-cloud-aiplatform = "~=1.50"

[project.optional-dependencies]
dev = [
    "ruff~=0.4",
    "pytest~=8.2"
]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "W", "F", "I", "C", "B"]